# Generated by Django 3.1.1 on 2020-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ManyToManyField(to='managment.Tag'),
        ),
    ]
